# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Face_Painting'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main_GUI(object):
    def setupUi(self, Main_GUI):
        Main_GUI.setObjectName("Main_GUI")
        Main_GUI.resize(1000, 600)
        self.label = QtWidgets.QLabel(Main_GUI)
        self.label.setGeometry(QtCore.QRect(295, 10, 410, 170))
        self.label.setAutoFillBackground(True)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Main_GUI)
        self.layoutWidget.setGeometry(QtCore.QRect(750, 70, 220, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(True)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.arm_state = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.arm_state.setFont(font)
        self.arm_state.setAutoFillBackground(True)
        self.arm_state.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arm_state.setObjectName("arm_state")
        self.horizontalLayout_6.addWidget(self.arm_state)
        self.layoutWidget1 = QtWidgets.QWidget(Main_GUI)
        self.layoutWidget1.setGeometry(QtCore.QRect(820, 150, 152, 401))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_6.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_9.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_10.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.layoutWidget2 = QtWidgets.QWidget(Main_GUI)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 150, 152, 401))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_7.setMinimumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.layoutWidget3 = QtWidgets.QWidget(Main_GUI)
        self.layoutWidget3.setGeometry(QtCore.QRect(230, 190, 533, 36))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.angle1 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.angle1.setFont(font)
        self.angle1.setAutoFillBackground(True)
        self.angle1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.angle1.setObjectName("angle1")
        self.horizontalLayout.addWidget(self.angle1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.angle2 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.angle2.setFont(font)
        self.angle2.setAutoFillBackground(True)
        self.angle2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.angle2.setObjectName("angle2")
        self.horizontalLayout_2.addWidget(self.angle2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.angle3 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.angle3.setFont(font)
        self.angle3.setAutoFillBackground(True)
        self.angle3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.angle3.setObjectName("angle3")
        self.horizontalLayout_3.addWidget(self.angle3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(Main_GUI)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(Main_GUI)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_11 = QtWidgets.QPushButton(Main_GUI)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 20, 111, 43))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_11.setObjectName("pushButton_11")
        self.comboBox = QtWidgets.QComboBox(Main_GUI)
        self.comboBox.setGeometry(QtCore.QRect(130, 70, 111, 43))
        self.comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox.setObjectName("comboBox")
        self.label_7 = QtWidgets.QLabel(Main_GUI)
        self.label_7.setGeometry(QtCore.QRect(130, 120, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Main_GUI)
        self.label_9.setGeometry(QtCore.QRect(860, 120, 110, 20))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.widget = QtWidgets.QWidget(Main_GUI)
        self.widget.setGeometry(QtCore.QRect(752, 21, 185, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(True)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.pump_state = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pump_state.setFont(font)
        self.pump_state.setAutoFillBackground(True)
        self.pump_state.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pump_state.setObjectName("pump_state")
        self.horizontalLayout_5.addWidget(self.pump_state)

        self.retranslateUi(Main_GUI)
        self.pushButton.clicked.connect(Main_GUI.initialization)
        self.pushButton_2.clicked.connect(Main_GUI.teach)
        self.pushButton_3.clicked.connect(Main_GUI.write)
        self.pushButton_4.clicked.connect(Main_GUI.memory_teach)
        self.pushButton_5.clicked.connect(Main_GUI.get_angle)
        self.pushButton_6.clicked.connect(Main_GUI.write_demo)
        self.pushButton_7.clicked.connect(Main_GUI.draw)
        self.pushButton_8.clicked.connect(Main_GUI.draw_demo)
        self.pushButton_9.clicked.connect(Main_GUI.open_draw_board)
        self.pushButton_10.clicked.connect(Main_GUI.open_write_board)
        self.pushButton_11.clicked.connect(Main_GUI.port_check)
        self.comboBox.currentTextChanged.connect(Main_GUI.port_imf)
        QtCore.QMetaObject.connectSlotsByName(Main_GUI)

    def retranslateUi(self, Main_GUI):
        _translate = QtCore.QCoreApplication.translate
        Main_GUI.setWindowTitle(_translate("Main_GUI", "HG_Desk_Arm"))
        self.label.setText(_translate("Main_GUI", "logo"))
        self.label_10.setText(_translate("Main_GUI", "机械臂状态:"))
        self.arm_state.setText(_translate("Main_GUI", "非工作状态"))
        self.pushButton_4.setText(_translate("Main_GUI", "记忆示教"))
        self.pushButton_6.setText(_translate("Main_GUI", "写字Demo"))
        self.pushButton_8.setText(_translate("Main_GUI", "画画Demo"))
        self.pushButton_9.setText(_translate("Main_GUI", "打开画板"))
        self.pushButton_10.setText(_translate("Main_GUI", "打开写字板"))
        self.pushButton.setText(_translate("Main_GUI", "初始化"))
        self.pushButton_5.setText(_translate("Main_GUI", "获取关节角度"))
        self.pushButton_2.setText(_translate("Main_GUI", "示教"))
        self.pushButton_3.setText(_translate("Main_GUI", "写字"))
        self.pushButton_7.setText(_translate("Main_GUI", "画画"))
        self.label_2.setText(_translate("Main_GUI", "关节一角度:"))
        self.angle1.setText(_translate("Main_GUI", "0.000"))
        self.label_3.setText(_translate("Main_GUI", "关节二角度:"))
        self.angle2.setText(_translate("Main_GUI", "0.000"))
        self.label_4.setText(_translate("Main_GUI", "关节三角度:"))
        self.angle3.setText(_translate("Main_GUI", "0.000"))
        self.label_8.setText(_translate("Main_GUI", "气泵状态:"))
        self.pump_state.setText(_translate("Main_GUI", "非工作状态"))
        self.label_6.setText(_translate("Main_GUI", "串口选择："))
        self.label_5.setText(_translate("Main_GUI", "串口检测："))
        self.pushButton_11.setText(_translate("Main_GUI", "检测串口"))

        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_11.setFocusPolicy(QtCore.Qt.NoFocus)