# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memory_teach.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_memory_teach(object):
    def setupUi(self, memory_teach):
        memory_teach.setObjectName("memory_teach")
        memory_teach.resize(827, 583)
        font = QtGui.QFont()
        font.setPointSize(13)
        memory_teach.setFont(font)
        # memory_teach.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # memory_teach.setFrameShadow(QtWidgets.QFrame.Raised)
        self.listView = QtWidgets.QListView(memory_teach)
        self.listView.setGeometry(QtCore.QRect(260, 340, 281, 221))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.listView.setFont(font)
        self.listView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listView.setObjectName("listView")
        self.pushButton_3 = QtWidgets.QPushButton(memory_teach)
        self.pushButton_3.setGeometry(QtCore.QRect(438, 110, 198, 210))
        self.pushButton_3.setMinimumSize(QtCore.QSize(150, 210))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_3.setObjectName("pushButton_3")
        self.layoutWidget = QtWidgets.QWidget(memory_teach)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 614, 102))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.layoutWidget1 = QtWidgets.QWidget(memory_teach)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 110, 412, 210))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_7.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.layoutWidget2 = QtWidgets.QWidget(memory_teach)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 340, 224, 220))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 3, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(memory_teach)
        self.pushButton_9.setGeometry(QtCore.QRect(640, 10, 161, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(memory_teach)
        self.pushButton_10.setGeometry(QtCore.QRect(640, 110, 161, 208))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_10.setObjectName("pushButton_10")
        self.listView_2 = QtWidgets.QListView(memory_teach)
        self.listView_2.setGeometry(QtCore.QRect(550, 340, 251, 221))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.listView_2.setFont(font)
        self.listView_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listView_2.setObjectName("listView_2")

        self.retranslateUi(memory_teach)
        self.pushButton.clicked.connect(memory_teach.get_current_angle)
        self.pushButton_2.clicked.connect(memory_teach.record_current_angle)
        self.pushButton_3.clicked.connect(memory_teach.clear_last_operate)
        self.pushButton_4.clicked.connect(memory_teach.finish_teach)
        self.pushButton_5.clicked.connect(memory_teach.start_new_teach)
        self.pushButton_6.clicked.connect(memory_teach.save_now_teach)
        self.pushButton_7.clicked.connect(memory_teach.pump_up)
        self.pushButton_8.clicked.connect(memory_teach.pump_down)
        self.pushButton_9.clicked.connect(memory_teach.exit_teach_interface)
        self.pushButton_10.clicked.connect(memory_teach.clear_all_operate)
        QtCore.QMetaObject.connectSlotsByName(memory_teach)

    def retranslateUi(self, memory_teach):
        _translate = QtCore.QCoreApplication.translate
        memory_teach.setWindowTitle(_translate("memory_teach", "记忆示教"))
        self.pushButton_3.setText(_translate("memory_teach", "清除上一个操作"))
        self.pushButton_5.setText(_translate("memory_teach", "新建示教任务"))
        self.pushButton_4.setText(_translate("memory_teach", "结束当前示教任务"))
        self.pushButton_6.setText(_translate("memory_teach", "保存当前示教任务"))
        self.pushButton.setText(_translate("memory_teach", "获取当前关节值"))
        self.pushButton_2.setText(_translate("memory_teach", "记录当前关节值"))
        self.pushButton_7.setText(_translate("memory_teach", "气泵吸气"))
        self.pushButton_8.setText(_translate("memory_teach", "气泵放气"))
        self.lineEdit_5.setText(_translate("memory_teach", "当前关节二角度"))
        self.lineEdit_4.setText(_translate("memory_teach", "当前关节一角度"))
        self.lineEdit_6.setText(_translate("memory_teach", "当前关节三角度"))
        self.lineEdit_7.setText(_translate("memory_teach", "当前的气泵状态"))
        self.pushButton_9.setText(_translate("memory_teach", "退出记忆示教功能"))
        self.pushButton_10.setText(_translate("memory_teach", "清除所有操作"))

        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_10.setFocusPolicy(QtCore.Qt.NoFocus)

